In [2]:
import torch
import numpy

In [5]:
print(torch.__version__)
print(numpy.__version__)

1.10.2
1.21.2


In [11]:
a = torch.tensor([[1, 4, 2], [3, 1, 1], [-2, 2, 3]], dtype=torch.float32)
print(a)
torch.linalg.det(a)

tensor([[ 1.,  4.,  2.],
        [ 3.,  1.,  1.],
        [-2.,  2.,  3.]])


tensor(-27.)

In [21]:
a = torch.tensor([[11, 12, 13, 14], 
                  [21, 22, 23, 24], 
                  [31, 32, 33, 34], 
                  [41, 42, 43, 44]], dtype=torch.float64)
print(a)
res = torch.linalg.det(a)
print(torch.round(res))

tensor([[11., 12., 13., 14.],
        [21., 22., 23., 24.],
        [31., 32., 33., 34.],
        [41., 42., 43., 44.]], dtype=torch.float64)
tensor(0., dtype=torch.float64)


In [4]:
a = torch.tensor([[1, 4, 2], 
                  [3, 1, 1], 
                  [-2, 2, 3]], dtype=torch.float64)
print(a)
res = torch.linalg.det(a)
print(res)

tensor([[ 1.,  4.,  2.],
        [ 3.,  1.,  1.],
        [-2.,  2.,  3.]], dtype=torch.float64)
tensor(-27.0000, dtype=torch.float64)


In [5]:
a = torch.tensor([[0, 1, 1, 1], 
                  [2, 0, 1, 1], 
                  [2, 2, 0, 1], 
                  [2, 2, 2, 0]], dtype=torch.float64)
print(a)
res = torch.linalg.det(a)
print(torch.round(res))


tensor([[0., 1., 1., 1.],
        [2., 0., 1., 1.],
        [2., 2., 0., 1.],
        [2., 2., 2., 0.]], dtype=torch.float64)
tensor(-14., dtype=torch.float64)


In [7]:
# solve linear equation
A = torch.tensor([[1, 4, 2],
                  [3, -2, 5],
                  [-2, -1, -3]], dtype=torch.float64)
B = torch.tensor([4, 2, 1], dtype=torch.float64)
torch.linalg.solve(A, B)

tensor([-12.5714,   0.1429,   8.0000], dtype=torch.float64)