In [16]:
# LU Decomposition

import pprint
import numpy as np
import scipy

A = np.array([ [7, 3, -1], [3, 8, 1], [-1, 1, 4], [2, -4, -1] ])

P, L, U = scipy.linalg.lu(A)

print("A: ")
pprint.pprint(A)

print("P: ")
pprint.pprint(P)

print("L: ")
pprint.pprint(L)

print("U: ")
pprint.pprint(U)


A: 
array([[ 7,  3, -1],
       [ 3,  8,  1],
       [-1,  1,  4],
       [ 2, -4, -1]])
P: 
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L: 
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ],
       [ 0.28571429, -0.72340426,  0.08982036]])
U: 
array([[ 7.        ,  3.        , -1.        ],
       [ 0.        ,  6.71428571,  1.42857143],
       [ 0.        ,  0.        ,  3.55319149]])


In [75]:
def mult_matrix(M, N):
    """Multiply square matrices of same dimension M and N"""
    assert len(M[0]) == len(N)
    # Converts N into a list of tuples of columns (You have to save them in the memory)
    tuple_N = list(zip(*N))
    
    # Nested list comprehension to calculate matrix multiplication                                                                                                                                                                                     
    return [[sum(el_m * el_n for el_m, el_n in zip(row_m, col_n)) for col_n in tuple_N] for row_m in M]

M = [[1, 2], [-1, 2]]
N = [[3, 2]]

In [76]:
mult_matrix(M, N)

AssertionError: 

In [79]:
# Choleski's decomposition
# LU Decomposition

import pprint
import numpy as np
import scipy

A = np.array([ [7, 3, -1, 4], [3, 8, 1, 2], [-1, 1, 4, 1], [2, -4, -1, 2] ])

P, L, U = np.linalg.cholesky(A)

print("A: ")
pprint.pprint(A)

print("P: ")
pprint.pprint(P)

print("L: ")
pprint.pprint(L)

print("U: ")
pprint.pprint(U)

LinAlgError: Matrix is not positive definite

# 기본행 연산 numpy로 하기

In [36]:
import numpy as np
import copy
import fractions

In [2]:
A = np.array([ [1, 1, 0], [1, 0, 0], [1, 2, 100]])

In [3]:
A[1] = A[0] * (-1) + A[1]

In [4]:
A

array([[  1,   1,   0],
       [  0,  -1,   0],
       [  1,   2, 100]])

In [27]:
A = np.array([ [0, 1, 0, 1, 0], [1, 0, 1, 0, 0], [0, 1, 1, 0, 0], [0, 0, 0, 1, 1], [0, 0, 0, 0, 1] ])
A

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

In [28]:
A[3] -= A[4]
tmp = copy.deepcopy(A[0])
A[0] = A[1]
A[1] = tmp
A

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
A[2] -= A[1]
A[2] += A[3]
A

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
A[0] -= A[2]
A[1] -= A[3]
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
A = np.array([ [1, 1, -1], [2, 3, 1], [4, 1, 2] ])
np.linalg.inv(A)

array([[ 0.33333333, -0.2       ,  0.26666667],
       [ 0.        ,  0.4       , -0.2       ],
       [-0.66666667,  0.2       ,  0.06666667]])

In [38]:
[[fractions.Fraction.from_float(elem).limit_denominator(1000) for elem in row] for row in np.linalg.inv(A)]

[[Fraction(1, 3), Fraction(-1, 5), Fraction(4, 15)],
 [Fraction(0, 1), Fraction(2, 5), Fraction(-1, 5)],
 [Fraction(-2, 3), Fraction(1, 5), Fraction(1, 15)]]